### PR TITLE
Require capitalize from titles

### LINKED ISSUE #13: Require capitalize from titles
Our [PR title pattern](https://zattoo2.atlassian.net/wiki/spaces/WEB/pages/2068807989/Pull+Request#Title) defines starting letter of sentence as capital. Issuer should fail with meaningful error if provided title is different.

### PR DESCRIPTION
**Pull request by nitzanashi**
Closes #13 

image
image

### CODE REVIEW

**Comment by gotbahn** [comment]
tests are red, otherwise looks good

**Comment by nitzanashi** [comment]
@gotbahn PTAL

**Comment by gotbahn** [comment]
Public Transport Accessibility Level

**Review by gotbahn — APPROVED** [review]

**Comment by nitzanashi** [comment]
Please take another look I learned it from @jeniamoroz

**Pull request merged**
